---
- name: Update dnf
  dnf:
    name: "*"
    state: latest

- name: Install Packages using dnf
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
   - terminator
   - zsh
   - vim
   - powertop
   - htop
   - git
   
